### ISSUE TITLE
some files can't be opened

### ISSUE THREAD

**Issue by mpowend** [benquick123/Edge-PDF-Reader#1]
When opening some files, instead of the address of the pdf, window's header is an irrelevant nonexistent .lnk file and this screen is shown:
![image](https://user-images.githubusercontent.com/6348644/208254079-88fcc303-f332-4101-b22a-a0cbd14e03d8.png)
upon further testing some files have this behavior when opened from windows explorer, but open normally when opened from other applications (everything search and calibre for example). some files show this regardless of where I open them from.
Notably, these files are opened normally when I try to open them with edge itself.
I am using windows 10 and edge 108.0.1462.42
any ideas?

**Comment by benquick123** [comment]
In my experience, files containing any special characters can't be opened (I live in a predominantly English-speaking world so this is not a problem). I haven't found a fix for this yet.

Beside from that, try increasing the timeout [here](https://github.com/benquick123/Edge-PDF-Standalone-Reader/blob/main/msedge.bat#L50) and recompiling. It might happen that the temporary shortcut gets deleted before it is opened by Edge.

These are the two ideas I have, although the issue might be somewhere else completely.

**Comment by mpowend** [comment]
Thank you. It was the first issue you stated in my case. the folder containing the file had "(12)" in its name. when deleted it worked as normal.
