### ISSUE TITLE
Request to make an independent application

### ISSUE THREAD

**Issue by Rushikesh-Malave-175** [benquick123/Edge-PDF-Reader#4]
I love MS Edge's PDF reader. But for the browser itself, I use another browser as my default. I consider Edge to be 'bloatware' and would love to just uninstall it completely and save that extra CPU and 1.5 gig of storage.

Please make an independent app for this. Like if you could extract just the pdf reader from MS edge and make an independent pdf viewer, it would be great. I'd uninstall Edge, and still be able to use its pdf viewer

**Comment by benquick123** [comment]
Although I do think making a standalone application can be done, I would assume that Edge's PDF reader is closely integrated with the browser itself; look at "Ask AI" button integrated in the viewer that opens Edge's Copilot for example. 

While this is not an endeavor for me, I sure hope that Microsoft will at some point decide and make it standalone.
