### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by elmerg999** [benquick123/Edge-PDF-Reader#5]
Hi there.

Windows Version	10.0.19045 Build 19045

I got some issues w/Compatibility that I was able to fix, but I can't get the exe to actually work. 

How do you actually use this? You have the exe creator, two different exes, an ico file and other files in your full list and the instructions are very vague. Your updates at the bottom mention something about an install to AppData, but nothing seems to try to do that when I run msedge_pdf.exe, either by itself or using 'open file using' to open a PDF using it to test. When I run the program manually to test, I get 'file not found' window with a a big long shortcut from the AppData folder that it can't find. So I'm not sure how that's supposed to install.

More detailed instructions would be helpful.

**Comment by elmerg999** [comment]
Actually, my question is probably better as:
How do you actually use this? You have the exe creator, two different exes, an ico file and other files in your full list and the instructions are very vague.

Which exe do I put in with the msedge file? I finally was able to get it to open and it says 'file not found' with no context, though the window has a big long piece of text with shortcut.lnk at the end. 

A more detailed 'how to use' would be very helpful.

**Comment by elmerg999** [comment]
Well, apparently fortieth try is the charm. It's now working properly with my PDFs, though the UTF-8 option didn't fix the special characters issue (PDFs have square brackets around part of the name to denote an order of reading, which causes failure even with the UTF-8 beta activated).

**Comment by benquick123** [comment]
I will keep this as closed, since it is working for you now, but let me just mention that opening files with special characters (even with square brackets) fully works for me. See the screenshot:
![image](https://github.com/benquick123/Edge-PDF-Standalone-Reader/assets/15819753/efad8e30-347e-4f84-bcaf-64ec694beb5a)
